<a href="https://colab.research.google.com/github/QuratAkhter/GenAI/blob/main/GenAI_Data_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'text': ['People watch Tom and Jerry', 'Tom and Jerry watch Tom and Jerry',
             'People write comment', 'Tom and Jerry write comment'],
    'output': [1,1,0,0]
})

In [3]:
df

text  output
0         People watch Tom and Jerry       1
1  Tom and Jerry watch Tom and Jerry       1
2               People write comment       0
3        Tom and Jerry write comment       0

# Bag of Words (BoW)

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer()

In [7]:
bow = cv.fit_transform(df['text'])

In [10]:
cv.vocabulary_

{'people': 3,
 'watch': 5,
 'tom': 4,
 'and': 0,
 'jerry': 2,
 'write': 6,
 'comment': 1}

In [11]:
bow.toarray()

array([[1, 0, 1, 1, 1, 1, 0],
       [2, 0, 2, 0, 2, 1, 0],
       [0, 1, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 1, 0, 1]])

In [12]:
cv.transform(['Annie watch Tom and Jerry']).toarray()

array([[1, 0, 1, 0, 1, 1, 0]])

# n-Gram

In [13]:
cv2 = CountVectorizer(ngram_range=(2,2))

In [16]:
ngram = cv2.fit_transform(df['text'])

In [17]:
cv2.vocabulary_

{'people watch': 3,
 'watch tom': 6,
 'tom and': 5,
 'and jerry': 0,
 'jerry watch': 1,
 'people write': 4,
 'write comment': 7,
 'jerry write': 2}

In [18]:
ngram.toarray()

array([[1, 0, 0, 1, 0, 1, 1, 0],
       [2, 1, 0, 0, 0, 2, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 1]])

In [19]:
cv2.transform(['Annie write comment']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1]])

# TF-IDF

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
tfidf = TfidfVectorizer()

In [22]:
arr = tfidf.fit_transform(df['text']).toarray()

In [23]:
arr

array([[0.40650968, 0.        , 0.40650968, 0.50212033, 0.40650968,
        0.50212033, 0.        ],
       [0.54381334, 0.        , 0.54381334, 0.        , 0.54381334,
        0.33585883, 0.        ],
       [0.        , 0.57735027, 0.        , 0.57735027, 0.        ,
        0.        , 0.57735027],
       [0.40650968, 0.50212033, 0.40650968, 0.        , 0.40650968,
        0.        , 0.50212033]])

In [25]:
tfidf.idf_

array([1.22314355, 1.51082562, 1.22314355, 1.51082562, 1.22314355,
       1.51082562, 1.51082562])

# Word2Vec

It is a deep learning based method that understand the semantic information

In [27]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 27.2 MB/s eta 0:00:00


In [28]:
import gensim
import os

In [29]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [30]:
story = []

for filename in os.listdir('data'):
    if filename == '.ipynb_checkpoints':
      pass
    f = open(os.path.join('data',filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
      story.append(simple_preprocess(sent))

In [31]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [32]:
len(story)

27244

In [33]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [34]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [35]:
model.build_vocab(story)

In [36]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(1058775, 1423500)

In [40]:
model.wv.most_similar('tom')

[('qotho', 0.9969507455825806),
 ('tarly', 0.9964885711669922),
 ('syrio', 0.9962263107299805),
 ('samwell', 0.9961528182029724),
 ('hallis', 0.9958780407905579),
 ('confused', 0.9956449270248413),
 ('marillion', 0.9954540133476257),
 ('noye', 0.995293915271759),
 ('morrec', 0.9952493906021118),
 ('jhogo', 0.9952190518379211)]

In [41]:
model.wv.most_similar('dothraki')

[('slaves', 0.994745671749115),
 ('wild', 0.9939066171646118),
 ('woods', 0.9936704635620117),
 ('summer', 0.9936244487762451),
 ('riders', 0.9935575723648071),
 ('eating', 0.99354088306427),
 ('sight', 0.9932969212532043),
 ('music', 0.9924873113632202),
 ('brigands', 0.9924785494804382),
 ('suckling', 0.9919556379318237)]

In [42]:
### Visualizing the vectors

from sklearn.decomposition import PCA

In [43]:
vec = model.wv.get_normed_vectors()

In [44]:
vec.shape

(7432, 100)

In [45]:
pca = PCA(n_components=3)

In [46]:
X = pca.fit_transform(vec)

In [47]:
X

array([[-0.3550833 , -0.18974674,  0.3000612 ],
       [-0.46109033, -0.0721392 ,  0.21914141],
       [ 0.44523627, -0.16637152, -0.07325441],
       ...,
       [ 0.3199361 , -0.7216472 , -0.19435483],
       [ 0.5670938 , -0.4920436 ,  0.5381833 ],
       [-0.16815661, -0.0136835 ,  0.05290517]], dtype=float32)

In [48]:
X.shape

(7432, 3)

In [51]:
import plotly.express as px

fig = px.scatter_3d(X, x=0, y=1, z=2)
fig.show()